export type CampaignStatus = "not-started" | "in-progress" | "completed"
export type Platform = "instagram" | "tiktok" | "threads" | "x"
export type TargetingMode = "date" | "posts"

export interface CommentCampaign {
  id: string // UUID generated by Supabase
  campaign_id: string // Custom campaign ID (e.g., campaign_abc12345_1702475982)
  custom_comment: string
  platform: Platform
  user_accounts: string[]
  target_profiles: string[]
  targeting_mode: TargetingMode
  target_date: string | null // ISO string or null
  number_of_posts: number | null
  status: CampaignStatus
  queue_position: number | null // Position in the queue
  created_at: string // ISO timestamp
  updated_at: string // ISO timestamp
}
